### ISSUE TITLE
Would you like to move this repo into the alexa-js organization?

### ISSUE THREAD

**Issue by dblock** [mandnyc/ssml-builder#3]
In theory SSML is not tied to Alexa in any way, but it's the current main use case. I also think we should probably provide better SSML support in the alexa-app library. 

Would you like to move this repo into the newly created alexa-js organization, https://github.com/alexa-js?

This would reduce bus factor as currently only @mandnyc can add contributors to this project and make it more discoverable. By moving org admins can at least add new people, currently that's @matt-kruse, @mreinstein and myself.

There's no other purpose. There will be no changes "forced" on you or any other additional help should be expected from "the organization", so nothing would change other than the above.

If you do want to do this, because Github requires one be admin of both source and destination, transfer the repo to me (@dblock) and I'll immediately move it to the org.

**Comment by mreinstein** [comment]
actually to be honest I don't think this repo belongs in alexa-js as an organization. SSML is a standardized language that is not specific to just Alexa.

**Comment by mreinstein** [comment]
if this module truly is just servicing the alexa subset of SSML, it would be good to rename the repo to `alexa-ssml-builder` to make that more clear.

**Comment by dblock** [comment]
I agree @mreinstein, I don't feel (too) strongly about this.

**Comment by mreinstein** [comment]
@dblock I'm not saying don't merge it in, I guess my question is, is this alexa specific? if it truly is then sure it would be great to throw it under the `alexa-js` maintenance umbrella.

**Comment by dblock** [comment]
Totally, I am completely agreeing with you - lets leave it to @mandnyc to decide - if this repo is only about Alexa, then it should be renamed and we can move it. But as is I vote to leave it alone.

**Comment by Tribex** [comment]
Just to add my two cents, I've been making basic use of this module for both an Alexa skill and a Google Assistant Action with a great deal of success.

**Comment by mandnyc** [comment]
@dblock @mreinstein - The real purpose of SSML-Builder is to focus on building SSML. Although it was originally designed to work with Alexa, it can also be used for Actions on Google and other APIs. 

@Tribex - What do you think it is missing from the project? Can you clarify the issues you are running into? You mentioned about the internationalization. Can you give me more details on that?

**Comment by Tribex** [comment]
@mandnyc Nothing is missing or causing trouble in particular. I actually love the module.

The reason I'm migrating to SSML strings is that many of the things I am having read out have multiple sentences and it's just much easier to store the version with SSML in the locale files. Pauses may need to be in different places depending on the language, and an internationalized multiple-sentence string doesn't map very well to a chainable API. :/
