### ISSUE TITLE
pause() regex needs updating

### ISSUE THREAD

**Issue by pauljperry** [mandnyc/ssml-builder#4]
The pause() function can take floating point values.  For example, specifying '.5s' is perfectly fine for the SSML to specify a half a second delay.  Unfortunately, the regex that does the validity check in  does not allow floating point values and throws an exception.  For me, I just commented out the call to _validateDuration(),  however that defeats the well-meant validation check.  Reviewing the SSML docs for the break tag does not make it clear if floating point values are allowed, but in practice, Alexa supports them.  I guess workaround would be to specify half a second in milliseconds instead.

**Comment by mandnyc** [comment]
Thanks Paul! I just released a minor update that corrects this problem.
